import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRecoilState } from 'recoil'

import { userState } from '../src/recoil/user.atom'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [user, setUser] = useRecoilState(userState)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <pre>{JSON.stringify(user, null, 2)}</pre>

      </main>

      <footer className={styles.footer}>
        GARY
      </footer>
    </div>
  )
}

export default Home
